### ISSUE TITLE
Configurable acceptable project score

### ISSUE THREAD

**Issue by WobblyRobbly** [PicnicSupermarket/dbt-score#55]
Hi

It would be good if we could set either 

- a minimum project score 
- minimum required severity

and have `dbt-score` return a non-zero return code so that we can stop CI pipelines. At the minute, only the inability to find a manifest file returns a non-zero return code. Duplicate rules raise an exception

e.g. for minimum required project score 

```
[tool.dbt-score]
min_required_project_score=7.5
```

or passed on command line `--min_required_project_score 7.5`

for maximum allowed severity

```
[tool.dbt-score]
min_required_severity=MEDIUM
```
or passed on command line `--min_required_severity MEDIUM`

Should it raise an exception or simply log a message and exit with non-zero return code ?

Regards
Rob

**Comment by matthieucan** [comment]
We should absolutely do this, yes! That's definitely how we envision it.

I would suggest something like

```
[tool.dbt-score]
fail_project_under = 7.5
fail_any_model_under = 6.0
```

meaning dbt-score would exit with 1 if either is true:
- the project score is below 7.5
- any model score is below 6.0

I think that would allow better control rather than `min_required_severity`.
Would such an approach work with your use-case?

**Comment by WobblyRobbly** [comment]
@matthieucan that would absolutely work !!
