### ISSUE TITLE
feature request: enable linting of sources

### ISSUE THREAD

**Issue by otosky** [PicnicSupermarket/dbt-score#76]
This is a super cool tool!

Is it on the roadmap to implement dbt sources as a lint-able node type?

I'd be happy to contribute a PR if that's something worthwhile to this project.

**Comment by matthieucan** [comment]
Glad to hear!
This is certainly something we'd love to have too, and would support. PRs welcome, but I'd encourage you to share design ideas and potential approaches here to ensure a smoother implementation later :)

**Comment by otosky** [comment]
Finally had some time to look back into this!

I think you've set up a great base for development here - my initial broad-stroke thoughts were to:

1. add the new dataclass for `SourceDefinition` - that's the dbt name for the type, but `Source` may be preferable? - in the models module
2. load the sources in the `ManifestLoader`
3. update the main loop in Evaluation.evaluate to iterate over all "evaluable" nodes.  For now, `Evaluable = Model | SourceDefinition`.
  i. all other methods elsewhere that just act on `Model`, should also be updated to act on `Evaluable` instead.

This leaves a possibility for extending evaluation out to any ManifestNode types, if that were desired.  For example, if one wanted to evaluate that Test nodes had particular tags, etc.

---

For my context, are there heuristics governing what fields are made public on the [Model](https://github.com/PicnicSupermarket/dbt-score/blob/d74cab7d802e00f0b28b78e346d73f79f7ec97d7/src/dbt_score/models.py#L121) dataclass (or any of the models in `models.py`)?  As opposed to the [models](https://github.com/dbt-labs/dbt-core/tree/v1.8.7/core/dbt/artifacts/resources/v1) packaged within dbt-core?  

Is the expectation that the dataclass fields should be a minimal set of compatible fields from v1.5 onwards?

**Comment by jochemvandooren** [comment]
Hey @otosky, thanks for getting back to us! :raised_hands: 

I think adding a `Source` dataclass and include the loading of sources in the `ManifestLoader` is the right approach. Also a great idea indeed to introduce the concept of `Evaluable` nodes. I can imagine we want to lint other objects in the future as well.

Some thinks we need to think about before implementation: do we think a rule should apply to models and sources by default? Maybe we need an easy way to distinguish this, as sources can have different properties etc. Also, it should be possible to filter certain sources, [just like models](https://github.com/PicnicSupermarket/dbt-score/blob/master/src/dbt_score/model_filter.py). 

> For my context, are there heuristics governing what fields are made public on the [Model](https://github.com/PicnicSupermarket/dbt-score/blob/d74cab7d802e00f0b28b78e346d73f79f7ec97d7/src/dbt_score/models.py#L121) dataclass (or any of the models in models.py)? As opposed to the [models](https://github.com/dbt-labs/dbt-core/tree/v1.8.7/core/dbt/artifacts/resources/v1) packaged within dbt-core? Is the expectation that the dataclass fields should be a minimal set of compatible fields from v1.5 onwards?

We decided to not use the dataclasses from dbt because we found them too confusing/complex for our use-case. Therefore we decided ourselves what information should be abstracted from the manifest, so we could have an easy `Model` dataclass. We value simplicity because we think writing a rule should be easy! So we made sure to include properties that we think are important, but also added the [_raw_values](https://github.com/PicnicSupermarket/dbt-score/blob/d74cab7d802e00f0b28b78e346d73f79f7ec97d7/src/dbt_score/models.py#L144) so the whole node is actually available.

**Comment by matthieucan** [comment]
Adding my $0.02 to the brainstorm:

A good and simple way for rules to apply to models, sources or other entities could be dependency injection. What I mean with this is the idea of a rule declaring what it expects:

```python
@rule
def my_model_rule(model: Model) -> RuleViolation | None:
    ...

@rule
def my_source_rule(source: Source) -> RuleViolation | None:
    ...
```

If a rule expects a model, it's a model rule, applied to all models. If a rule expects a source, it's a source rule, applied to all sources.

This will also play well in the future when we introduce more power to rules. For example, having access to the entire manifest would enable new types of verifications:

```python
def my_model_rule(model: Model, manifest: Manifest) -> RuleViolation | None:
    # do some checks for this model that require access to the manifest too
```

**Comment by otosky** [comment]
@matthieucan - love that! This is what I was gonna suggest as well.

For rules that can apply to both, i.e. "a node has a `description`", how do you think that should be expressed?  Always explicit enumeration of types?  Accept an arbitrary `Protocol`?

**Comment by matthieucan** [comment]
I would keep it simple, at least for now, and do something like:
```python
def some_logic_for_both_model_and_source(entity: Model | Source) -> RuleViolation | None:
    ...

@rule
def my_model_rule(model: Model) -> RuleViolation | None:
    return some_logic_for_both_model_and_source(model)

@rule
def my_source_rule(source: Source) -> RuleViolation | None:
    some_logic_for_both_model_and_source(source)
```
What do you think?

**Comment by otosky** [comment]
@matthieucan that seems sound and is a good forcing-function to make rules specific and self-describing :+1:
